eureka:
  instance:
     preferIpAddress: true
  client:
    serviceUrl:
       defaultZone: http://eureka-server:8080/eureka/,http://eureka-server-dr:8080/eureka/


# Spring properties
spring:
  application:
     name: socialreview-microservice


# Server configuration
server:
  context-path: /micro
  port: 8080



# Cloudant Confiugration
cloudant:
    username: d51b69aa-f512-403a-a7a7-58da7aa7fac9-bluemix
    password: 07a74180f60025a9bc863a639f8d5035d49e9e4fa9ab96bd8d4fb0f3331f8159
    host: http://d51b69aa-f512-403a-a7a7-58da7aa7fac9-bluemix.cloudant.com

server:
  port: 8080

  